server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # React routing
  location / {
    try_files $uri /index.html;
  }

  # Reverse proxy
  location /api {
    proxy_pass http://backend:5000;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
  }
}
# NOTE::NOTE::NOTE::
# Why backend:5000 works

# 👉 Docker Compose creates a network:

# frontend container → can access → backend container using service name

# So:

# backend = hostname inside Docker network




# server {
#   listen 80;

#   root /usr/share/nginx/html;
#   index index.html;

#   location / {
#     try_files $uri /index.html;
#   }
# }