# using cached image

services:
  backend:
    image: backend:test

    command: sh -c "npx prisma migrate deploy && npm test"

# services:
#   backend:
#     build:
#       context: ./backend
#       target: test
#     command: sh -c "npx prisma migrate deploy && npm test"
